# Generated by Django 4.1.4 on 2022-12-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_name', models.CharField(max_length=100)),
                ('election_head', models.CharField(max_length=100)),
                ('election_date', models.DateField()),
                ('election_picture', models.ImageField(upload_to='images/')),
                ('constituency', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('voter_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'elction_detials',
            },
        ),
        migrations.CreateModel(
            name='VoterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('aadhar', models.ImageField(upload_to='aadhar/')),
                ('city', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'voters_details',
            },
        ),
        migrations.CreateModel(
            name='CandidateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('party_name', models.CharField(max_length=100)),
                ('symbol', models.ImageField(upload_to='symbols/')),
                ('votes', models.IntegerField(default=0)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_candidates', to='adminapp.electionmodel')),
                ('voters', models.ManyToManyField(related_name='voted_voters', to='adminapp.votermodel')),
            ],
            options={
                'db_table': 'candidate_details',
            },
        ),
    ]
