# Generated by Django 4.1.4 on 2022-12-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votermodel',
            name='aadhar',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
