# Generated by Django 4.1.4 on 2022-12-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_votermodel_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionmodel',
            name='voters',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.votermodel'),
        ),
    ]
