# Generated by Django 4.1.4 on 2022-12-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_electionmodel_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionmodel',
            name='voters',
        ),
        migrations.AddField(
            model_name='electionmodel',
            name='voters',
            field=models.ManyToManyField(to='adminapp.votermodel'),
        ),
    ]
