# Generated by Django 4.1.4 on 2022-12-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_electionmodel_voters_electionmodel_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electionmodel',
            old_name='voter_count',
            new_name='candidates_count',
        ),
        migrations.CreateModel(
            name='VotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_block', models.CharField(max_length=100)),
                ('candidate_block', models.CharField(max_length=100)),
                ('election_block', models.CharField(max_length=100)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates_votes', to='adminapp.candidatemodel')),
                ('election', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_votes', to='adminapp.electionmodel')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter_voted_list', to='adminapp.votermodel')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
    ]
