# Generated by Django 4.1.4 on 2022-12-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_rename_voter_count_electionmodel_candidates_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='votermodel',
            name='otp',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
