# Generated by Django 4.1.4 on 2022-12-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_votermodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='votermodel',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
