# Generated by Django 4.1.3 on 2022-12-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_votermodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='votermodel',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='votermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='votermodel',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='votermodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='votermodel',
            name='picture',
        ),
    ]
