# Generated by Django 4.1.3 on 2022-12-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_votermodel_city_remove_votermodel_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votermodel',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
